

services:
  gemini_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemini_node
    ports:
      - "11451:11451"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=production
